# Zenroom TP for Sawtooth experimental environment

version: '3'

services:

  zenroom-tp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    tty: true
    stdin_open: true
    image: zenroom-tp-python:devel
    container_name: zenroom-tp
    depends_on:
      - validator
    command: |
      bash -c "
        zenroom-tp-python
      "

  block-info-tp:
    image: hyperledger/sawtooth-block-info-tp:latest
    container_name: block-info-tp
    depends_on:
      - validator
    command: block-info-tp -vv --connect tcp://validator:4004

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:latest
    container_name: settings-tp
    depends_on:
      - validator
    command: settings-tp -vv --connect tcp://validator:4004

  rest-api:
    image: hyperledger/sawtooth-rest-api:latest
    container_name: rest-api
    ports:
      - '8090:8090'
    depends_on:
      - validator
    entrypoint: |
      sawtooth-rest-api -vv
        --connect tcp://validator:4004
        --bind rest-api:8090

  devmode-rust:
    image: hyperledger/sawtooth-devmode-engine-rust:latest
    container_name: devmode-engine-rust
    depends_on:
      - validator
    command: devmode-engine-rust -v --connect tcp://validator:5050

  validator:
    image: hyperledger/sawtooth-validator:latest
    container_name: sawtooth-validator
    ports:
      - '4004:4004/tcp'
      - 8800
    command: |
      bash -c "
        if [ ! -f /etc/keys/validator.priv ]; then
          sawadm keygen &&
          sawset genesis \
          -k /etc/sawtooth/keys/validator.priv \
          -o config-genesis.batch &&
        sawset proposal create \
          -k /etc/sawtooth/keys/validator.priv \
          sawtooth.consensus.algorithm.name=Devmode \
          sawtooth.consensus.algorithm.version=0.1 \
          sawtooth.validator.batch_injectors=block_info \
          -o config.batch &&
        sawadm genesis config-genesis.batch config.batch
        fi;
        sawtooth-validator -vv \
            --endpoint tcp://validator:8800 \
            --bind component:tcp://eth0:4004 \
            --bind network:tcp://eth0:8800 \
            --bind consensus:tcp://eth0:5050
      "

volumes:
  sawtooth:
